# Generated by Django 5.2.14 on 2026-05-17 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ps_price_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch', to='ps_price_sync.storeproduct')),
            ],
            options={
                'ordering': ['store_product__product_name', 'store_product__product_id'],
            },
        ),
    ]
