# Generated by Django 5.2.14 on 2026-05-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_price_sync', '0001_initial'),
        ('ps_price_web', '0001_watched_product'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('target_price_cents__isnull', True), ('target_price_cents__gt', 0), _connector='OR'), name='watched_product_target_price_positive_or_null'),
        ),
    ]
