# Generated by Django 5.2.14 on 2026-05-16 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=128, unique=True)),
                ('concept_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('product_name', models.TextField()),
                ('concept_name', models.TextField(blank=True, default='')),
                ('publisher_name', models.TextField(blank=True, null=True)),
                ('release_date_raw', models.TextField(blank=True, null=True)),
                ('top_category', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('platforms_raw', models.TextField(default='[]')),
                ('is_visible', models.BooleanField(blank=True, null=True)),
                ('missing_count', models.PositiveIntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=32)),
                ('product_id', models.CharField(blank=True, max_length=128, null=True)),
                ('concept_id', models.CharField(blank=True, max_length=64, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('error_type', models.CharField(max_length=128)),
                ('error_message', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='ps_price_sync.syncrun')),
            ],
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('normalized_state', models.CharField(max_length=32)),
                ('currency', models.CharField(blank=True, max_length=16, null=True)),
                ('base_amount_cents', models.IntegerField(blank=True, null=True)),
                ('discounted_amount_cents', models.IntegerField(blank=True, null=True)),
                ('plus_amount_cents', models.IntegerField(blank=True, null=True)),
                ('base_display', models.TextField(blank=True, null=True)),
                ('discounted_display', models.TextField(blank=True, null=True)),
                ('discount_text', models.TextField(blank=True, null=True)),
                ('service_branding_raw', models.TextField(default='[]')),
                ('upsell_text', models.TextField(blank=True, null=True)),
                ('source_strategy_source', models.CharField(max_length=32)),
                ('source_strategy_reason', models.CharField(max_length=64)),
                ('source_strategy_reason_codes_raw', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='ps_price_sync.storeproduct')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store_product', 'snapshot_date'), name='unique_snapshot_per_product_per_day')],
            },
        ),
    ]
